version: '3'
services:
  my-app:
    image: "jithendar/my-app:1.1"
    container_name: "my-app"
    ports:
      - 3000:3000
    restart: "unless-stopped"
  mongodb:
    image: "mongo"
    container_name: "mongo"
    ports:
      - 27017:27017
    restart: "unless-stopped"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: "mongo-express"
    container_name: "mongo-express"
    ports:
      - 8081:8081
    restart: "unless-stopped"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
